### ISSUE TITLE
Content-Type for old database

### ISSUE THREAD

**Issue by pravosleva** [soupette/fix-strapi-login#2]
![0_new-project-with-strapi-alpha](https://user-images.githubusercontent.com/19761493/44308024-49109900-a3b6-11e8-8e74-a0be220272e0.gif)
I have created new `strapi-alpha` project successfully.
And also I have my old remote database.
How can I create new Content-Type wich should be used with my old database?

**Comment by pravosleva** [comment]
This is my project
https://github.com/pravosleva/strapi-things-alpha

**Comment by pravosleva** [comment]
![img_20180819_140501](https://user-images.githubusercontent.com/19761493/44308207-7874d500-a3b9-11e8-96ec-d9e336b5027a.jpg)
I have problems when I try to create this by content-builder.

**Comment by pravosleva** [comment]
![img_20180819_141507](https://user-images.githubusercontent.com/19761493/44308257-72332880-a3ba-11e8-824c-e2c0b3200473.jpg)
And also, new user could not be created...

**Comment by pravosleva** [comment]
I want to create new content with the following fields
```
{
  header: srt,
  description: str,
  done: bool,
  priority: num,
}
```
And use socket.io like this: http://selection4test.ru:3003/blog/post/strapi-customization
Is it possible with new `strapi-alpha` version?

**Comment by pravosleva** [comment]
Hi.
3.0.0-alpha.13.1

**Comment by soupette** [comment]
What's your OS? Can you file an issue on https://github.com/strapi/strapi so we can fix it as a team ?

**Comment by pravosleva** [comment]
Ok, done.
